<?php

// This file was generated by running "composer dump-env dev"

return array (
  'APP_ENV' => 'dev',
  'APP_SECRET' => '537dd8de337e0ddf1302ea0232a93f5d',
  'DATABASE_URL' => 'mysql://root:example@db:3306/dockerFinal?serverVersion=8.0.36&charset=utf8mb4',
//  'DATABASE_URL' => 'mysql://root:example@127.0.0.1:3306/dockerFinal?serverVersion=8.0.36&charset=utf8mb4',
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default?auto_setup=0',
);
